id: P36FA48DB
initial_creation_type: ocr
source_metadata:
  volumes:
    6e4f0dddfa2746d6969c5b5b3a100f14:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: འཕགས་པ་ལག་ན་རྡོ་རྗེ་གོས་སྔོན་པོ་ཅན་གྱི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག་ཐམས་ཅད་རྫོགས་པ།
      total_pages: 1853
      volume_number: 25
